#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <MetalPerformanceShaders/MetalPerformanceShaders.h>
#include "num_metal.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <string>

struct num_metal_context { id<MTLDevice> device; id<MTLCommandQueue> queue; id<MTLLibrary> library; NSMutableDictionary* pipelines; std::string error; };
struct num_metal_kernel { id<MTLComputePipelineState> pipeline; };
static const char* bootstrap=R"MSL(
#include <metal_stdlib>
using namespace metal;
kernel void axpy(device const float*x[[buffer(0)]],device float*y[[buffer(1)]],constant float&a[[buffer(2)]],constant uint&n[[buffer(3)]],uint i[[thread_position_in_grid]]){if(i<n)y[i]+=a*x[i];}
kernel void scal(device float*x[[buffer(0)]],constant float&a[[buffer(1)]],constant uint&n[[buffer(2)]],uint i[[thread_position_in_grid]]){if(i<n)x[i]*=a;}
kernel void ewise(device const float*x[[buffer(0)]],device const float*y[[buffer(1)]],device float*z[[buffer(2)]],constant uint&n[[buffer(3)]],constant uint&op[[buffer(4)]],uint i[[thread_position_in_grid]]){if(i<n)z[i]=op==0?x[i]+y[i]:op==1?x[i]-y[i]:op==2?x[i]*y[i]:x[i]/y[i];}
kernel void reduction(device const float*x[[buffer(0)]],device const float*y[[buffer(1)]],device float*out[[buffer(2)]],constant uint&n[[buffer(3)]],constant uint&op[[buffer(4)]],constant uint&multiply[[buffer(5)]]){float r=op==1?-INFINITY:op==2?INFINITY:0.0f;for(uint i=0;i<n;i++){float q=multiply?x[i]*y[i]:x[i];r=op==0?r+q:op==1?max(r,q):min(r,q);}out[0]=r;}
kernel void gemv(device const float*A[[buffer(0)]],device const float*x[[buffer(1)]],device float*y[[buffer(2)]],constant uint2&mn[[buffer(3)]],constant float2&ab[[buffer(4)]],uint i[[thread_position_in_grid]]){if(i<mn.x){float s=0;for(uint j=0;j<mn.y;j++)s+=A[i*mn.y+j]*x[j];y[i]=ab.x*s+ab.y*y[i];}}
kernel void gemm(device const float*A[[buffer(0)]],device const float*B[[buffer(1)]],device float*C[[buffer(2)]],constant uint3&mkn[[buffer(3)]],constant float2&ab[[buffer(4)]],uint2 ij[[thread_position_in_grid]]){if(ij.y<mkn.x&&ij.x<mkn.z){float s=0;for(uint l=0;l<mkn.y;l++)s+=A[ij.y*mkn.y+l]*B[l*mkn.z+ij.x];uint q=ij.y*mkn.z+ij.x;C[q]=ab.x*s+ab.y*C[q];}}
kernel void spmv(device const int*rp[[buffer(0)]],device const int*ci[[buffer(1)]],device const float*v[[buffer(2)]],device const float*x[[buffer(3)]],device float*y[[buffer(4)]],constant uint&rows[[buffer(5)]],uint i[[thread_position_in_grid]]){if(i<rows){float s=0;for(int p=rp[i];p<rp[i+1];p++)s+=v[p]*x[ci[p]];y[i]=s;}}
)MSL";
static int fail(num_metal_context*c,int code,NSString*message){if(c)c->error=message.UTF8String;return code;}
static id<MTLBuffer> buf(void*p){return (__bridge id<MTLBuffer>)p;}
static id<MTLComputePipelineState> pipe(num_metal_context*c,NSString*name){id p=c->pipelines[name];if(p)return p;id<MTLFunction>f=[c->library newFunctionWithName:name];if(!f)return nil;NSError*e=nil;p=[c->device newComputePipelineStateWithFunction:f error:&e];if(p)c->pipelines[name]=p;else c->error=e.description.UTF8String;return p;}
static int run(num_metal_context*c,id<MTLComputePipelineState>p,void(^bindings)(id<MTLComputeCommandEncoder>),MTLSize grid,MTLSize group){if(!c||!p)return NUM_METAL_INVALID;id<MTLCommandBuffer>cb=[c->queue commandBuffer];id<MTLComputeCommandEncoder>e=[cb computeCommandEncoder];[e setComputePipelineState:p];bindings(e);[e dispatchThreads:grid threadsPerThreadgroup:group];[e endEncoding];[cb commit];[cb waitUntilCompleted];return cb.error?fail(c,NUM_METAL_RUNTIME,cb.error.description):NUM_METAL_OK;}
extern "C" int num_metal_create(num_metal_context**out){if(!out)return NUM_METAL_INVALID;id<MTLDevice>d=MTLCreateSystemDefaultDevice();if(!d)return NUM_METAL_RUNTIME;NSError*e=nil;id<MTLLibrary>l=[d newLibraryWithSource:@(bootstrap) options:nil error:&e];if(!l)return NUM_METAL_COMPILE;*out=new num_metal_context{d,[d newCommandQueue],l,[NSMutableDictionary dictionary],""};return NUM_METAL_OK;}
extern "C" int num_metal_destroy(num_metal_context*c){if(!c)return NUM_METAL_INVALID;delete c;return NUM_METAL_OK;}
extern "C" const char*num_metal_last_error(num_metal_context*c){return c?c->error.c_str():"null context";}
extern "C" int num_metal_device_name(num_metal_context*c,char*out,uint64_t cap){if(!c||!out||!cap)return NUM_METAL_INVALID;snprintf(out,cap,"%s",c->device.name.UTF8String);return NUM_METAL_OK;}
extern "C" int num_metal_malloc_f32(num_metal_context*c,uint64_t n,void**out){if(!c||!n||!out)return NUM_METAL_INVALID;id<MTLBuffer>b=[c->device newBufferWithLength:n*4 options:MTLResourceStorageModeShared];if(!b)return NUM_METAL_RUNTIME;*out=(__bridge_retained void*)b;memset(b.contents,0,n*4);return NUM_METAL_OK;}
extern "C" int num_metal_free(num_metal_context*c,void*p){if(!c||!p)return NUM_METAL_INVALID;CFRelease(p);return NUM_METAL_OK;}
extern "C" int num_metal_h2d_f32(num_metal_context*c,void*p,const float*x,uint64_t n){if(!c||!p||!x)return NUM_METAL_INVALID;memcpy(buf(p).contents,x,n*4);return NUM_METAL_OK;}
extern "C" int num_metal_d2h_f32(num_metal_context*c,float*x,void*p,uint64_t n){if(!c||!p||!x)return NUM_METAL_INVALID;memcpy(x,buf(p).contents,n*4);return NUM_METAL_OK;}
static MTLSize g1(uint32_t n){return MTLSizeMake(n,1,1);}static MTLSize t1(uint32_t n){return MTLSizeMake(std::min(n,256u),1,1);}
extern "C" int num_metal_axpy(num_metal_context*c,float a,void*x,void*y,uint32_t n){return run(c,pipe(c,@"axpy"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(x) offset:0 atIndex:0];[e setBuffer:buf(y) offset:0 atIndex:1];[e setBytes:&a length:4 atIndex:2];[e setBytes:&n length:4 atIndex:3];},g1(n),t1(n));}
extern "C" int num_metal_scal(num_metal_context*c,float a,void*x,uint32_t n){return run(c,pipe(c,@"scal"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(x) offset:0 atIndex:0];[e setBytes:&a length:4 atIndex:1];[e setBytes:&n length:4 atIndex:2];},g1(n),t1(n));}
extern "C" int num_metal_ewise(num_metal_context*c,int op,void*x,void*y,void*z,uint32_t n){uint32_t o=op;return run(c,pipe(c,@"ewise"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(x) offset:0 atIndex:0];[e setBuffer:buf(y) offset:0 atIndex:1];[e setBuffer:buf(z) offset:0 atIndex:2];[e setBytes:&n length:4 atIndex:3];[e setBytes:&o length:4 atIndex:4];},g1(n),t1(n));}
static int red(num_metal_context*c,int op,void*x,void*y,uint32_t n,float*out){void*o=nullptr;int s=num_metal_malloc_f32(c,1,&o);if(s)return s;uint32_t q=op,multiply=y?1:0;s=run(c,pipe(c,@"reduction"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(x) offset:0 atIndex:0];[e setBuffer:buf(y?y:x) offset:0 atIndex:1];[e setBuffer:buf(o) offset:0 atIndex:2];[e setBytes:&n length:4 atIndex:3];[e setBytes:&q length:4 atIndex:4];[e setBytes:&multiply length:4 atIndex:5];},g1(1),g1(1));if(!s)*out=((float*)buf(o).contents)[0];num_metal_free(c,o);return s;}
extern "C" int num_metal_dot(num_metal_context*c,void*x,void*y,uint32_t n,float*out){return red(c,0,x,y,n,out);}extern "C" int num_metal_nrm2(num_metal_context*c,void*x,uint32_t n,float*out){int s=red(c,0,x,x,n,out);if(!s)*out=sqrtf(*out);return s;}extern "C" int num_metal_reduce(num_metal_context*c,int op,void*x,uint32_t n,float*out){return red(c,op,x,nullptr,n,out);}
extern "C" int num_metal_gemv(num_metal_context*c,float a,void*A,uint32_t m,uint32_t n,void*x,float b,void*y){struct{uint32_t m,n;}mn{m,n};struct{float a,b;}ab{a,b};return run(c,pipe(c,@"gemv"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(A) offset:0 atIndex:0];[e setBuffer:buf(x) offset:0 atIndex:1];[e setBuffer:buf(y) offset:0 atIndex:2];[e setBytes:&mn length:sizeof(mn) atIndex:3];[e setBytes:&ab length:sizeof(ab) atIndex:4];},g1(m),t1(m));}
extern "C" int num_metal_gemm(num_metal_context*c,float a,void*A,uint32_t m,uint32_t k,void*B,uint32_t n,float b,void*C){struct{uint32_t m,k,n;}mkn{m,k,n};struct{float a,b;}ab{a,b};return run(c,pipe(c,@"gemm"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(A) offset:0 atIndex:0];[e setBuffer:buf(B) offset:0 atIndex:1];[e setBuffer:buf(C) offset:0 atIndex:2];[e setBytes:&mkn length:sizeof(mkn) atIndex:3];[e setBytes:&ab length:sizeof(ab) atIndex:4];},MTLSizeMake(n,m,1),MTLSizeMake(std::min(n,16u),std::min(m,16u),1));}
static MPSMatrix* matrix(void*p,uint32_t rows,uint32_t cols){MPSMatrixDescriptor*d=[MPSMatrixDescriptor matrixDescriptorWithRows:rows columns:cols rowBytes:cols*sizeof(float) dataType:MPSDataTypeFloat32];return [[MPSMatrix alloc]initWithBuffer:buf(p) descriptor:d];}
static int mps_mul(num_metal_context*c,float alpha,void*A,uint32_t m,uint32_t k,void*B,uint32_t n,float beta,void*C){if(!c||!A||!B||!C||!m||!k||!n)return NUM_METAL_INVALID;MPSMatrix*ma=matrix(A,m,k);MPSMatrix*mb=matrix(B,k,n);MPSMatrix*mc=matrix(C,m,n);MPSMatrixMultiplication*op=[[MPSMatrixMultiplication alloc]initWithDevice:c->device transposeLeft:false transposeRight:false resultRows:m resultColumns:n interiorColumns:k alpha:alpha beta:beta];id<MTLCommandBuffer>cb=[c->queue commandBuffer];[op encodeToCommandBuffer:cb leftMatrix:ma rightMatrix:mb resultMatrix:mc];[cb commit];[cb waitUntilCompleted];return cb.error?fail(c,NUM_METAL_RUNTIME,cb.error.description):NUM_METAL_OK;}
extern "C" int num_metal_mps_gemv(num_metal_context*c,float a,void*A,uint32_t m,uint32_t n,void*x,float b,void*y){return mps_mul(c,a,A,m,n,x,1,b,y);}
extern "C" int num_metal_mps_gemm(num_metal_context*c,float a,void*A,uint32_t m,uint32_t k,void*B,uint32_t n,float b,void*C){return mps_mul(c,a,A,m,k,B,n,b,C);}
extern "C" int num_metal_spmv(num_metal_context*c,uint32_t rows,uint32_t cols,uint32_t nnz,const int*rp,const int*ci,const float*v,void*x,void*y){id<MTLBuffer>br=[c->device newBufferWithBytes:rp length:(rows+1)*4 options:MTLResourceStorageModeShared],bc=[c->device newBufferWithBytes:ci length:nnz*4 options:MTLResourceStorageModeShared],bv=[c->device newBufferWithBytes:v length:nnz*4 options:MTLResourceStorageModeShared];return run(c,pipe(c,@"spmv"),^(id<MTLComputeCommandEncoder>e){[e setBuffer:br offset:0 atIndex:0];[e setBuffer:bc offset:0 atIndex:1];[e setBuffer:bv offset:0 atIndex:2];[e setBuffer:buf(x) offset:0 atIndex:3];[e setBuffer:buf(y) offset:0 atIndex:4];[e setBytes:&rows length:4 atIndex:5];},g1(rows),t1(rows));}
extern "C" int num_metal_compile(num_metal_context*c,const char*source,const char*name,num_metal_kernel**out){if(!c||!source||!name||!out)return NUM_METAL_INVALID;NSError*e=nil;id<MTLLibrary>l=[c->device newLibraryWithSource:@(source) options:nil error:&e];if(!l)return fail(c,NUM_METAL_COMPILE,e.description);id<MTLFunction>f=[l newFunctionWithName:@(name)];if(!f)return fail(c,NUM_METAL_COMPILE,@"function missing");id<MTLComputePipelineState>p=[c->device newComputePipelineStateWithFunction:f error:&e];if(!p)return fail(c,NUM_METAL_COMPILE,e.description);*out=new num_metal_kernel{p};return NUM_METAL_OK;}
extern "C" int num_metal_kernel_destroy(num_metal_context*c,num_metal_kernel*k){if(!c||!k)return NUM_METAL_INVALID;delete k;return NUM_METAL_OK;}
extern "C" int num_metal_launch_ewise(num_metal_context*c,num_metal_kernel*k,void*x,void*y,void*z,uint32_t n,uint32_t wg){return run(c,k->pipeline,^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(x) offset:0 atIndex:0];[e setBuffer:buf(y) offset:0 atIndex:1];[e setBuffer:buf(z) offset:0 atIndex:2];[e setBytes:&n length:4 atIndex:3];},g1(n),g1(wg));}
extern "C" int num_metal_launch_reduce(num_metal_context*c,num_metal_kernel*k,int op,void*x,uint32_t n,uint32_t wg,float*out){uint32_t parts=(n+wg-1)/wg;void*p=nullptr;int s=num_metal_malloc_f32(c,parts,&p);if(s)return s;s=run(c,k->pipeline,^(id<MTLComputeCommandEncoder>e){[e setBuffer:buf(x) offset:0 atIndex:0];[e setBuffer:buf(p) offset:0 atIndex:1];[e setBytes:&n length:4 atIndex:2];[e setThreadgroupMemoryLength:wg*4 atIndex:0];},g1(parts*wg),g1(wg));if(!s){float*r=(float*)buf(p).contents;float q=op==1?-INFINITY:op==2?INFINITY:0;for(uint32_t i=0;i<parts;i++)q=op==0?q+r[i]:op==1?std::max(q,r[i]):std::min(q,r[i]);*out=q;}num_metal_free(c,p);return s;}
